openapi: 3.0.3
info:
  title: Product Service
  description: |-
    API documentation for the Product Service for [my-shop app 🛒](https://github.com/RoierS/nodejs-aws-shop-react)
  version: 1.0.0
servers:
  - url: https://5je463g2q9.execute-api.eu-west-1.amazonaws.com
tags:
  - name: products
    description: Endpoints related to products
paths:
  /products:
    get:
      tags:
        - products
      summary: Get a list of all products
      description: Returns an array of all products
      operationId: getProductsList
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'          
        '500':
          description: Internal Server Error
  /products/{productId}:
    get:
      tags:
        - products
      summary: Get product by ID
      description: Returns a single product
      operationId: getProductById
      parameters:
        - name: productId
          in: path
          required: true
          description: The ID of the product to retrieve
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'          
        '400':
          description: Invalid ID supplied
        '404':
          description: Product not found
        '500':
          description: Internal server error
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          example: 7567ec4b-b10c-48c5-9345-fc73c48a80aa
        title:
          type: string
          example: ProductOne
        description:
          type: string
          example: Short Product Description1
        price:
          type: number
          example: 24